version: "3.8"
services:
  discord-bot:
    build: .
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - VC_CHANNEL_ID=${VC_CHANNEL_ID}
      - RADIO_URL=${RADIO_URL}
